In [34]:
import numpy as np
import pandas as pd
from unidecode import unidecode
from resolve_path import ajuste_path

In [35]:
pathInput = "data/input/"
pathInput = ajuste_path(pathInput)

df = pd.read_csv(pathInput + "BD_Acidentes_13_08.csv", sep="@", encoding="utf-8")
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1043 entries, 0 to 1042
Data columns (total 60 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Unnamed: 0                    1043 non-null   int64  
 1   Codigo                        1043 non-null   int64  
 2   Empregado                     1043 non-null   object 
 3   Classificação                 1043 non-null   object 
 4   Nexo causal                   1034 non-null   object 
 5   Empresa                       1043 non-null   object 
 6   Fornecedor                    526 non-null    object 
 7   Nº do Contrato                186 non-null    object 
 8   Segmento                      1043 non-null   object 
 9   ID                            886 non-null    object 
 10  Nome                          1002 non-null   object 
 11  Função                        992 non-null    object 
 12  Sexo                          989 non-null    object 
 13  Ida

## Pré processamento das colunas:

In [36]:
df.columns = df.columns.str.lower()
df.columns = df.columns.map(lambda x: unidecode(str(x)))
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1043 entries, 0 to 1042
Data columns (total 60 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   unnamed: 0                    1043 non-null   int64  
 1   codigo                        1043 non-null   int64  
 2   empregado                     1043 non-null   object 
 3   classificacao                 1043 non-null   object 
 4   nexo causal                   1034 non-null   object 
 5   empresa                       1043 non-null   object 
 6   fornecedor                    526 non-null    object 
 7   no do contrato                186 non-null    object 
 8   segmento                      1043 non-null   object 
 9   id                            886 non-null    object 
 10  nome                          1002 non-null   object 
 11  funcao                        992 non-null    object 
 12  sexo                          989 non-null    object 
 13  ida

## Pré processamento das linhas

### Utilitários

In [37]:
replace_dict = {
    "na": np.nan,
    "nan": np.nan,
    "n.a": np.nan,
    "n.a.": np.nan,
    "n/a": np.nan,
    "-": np.nan,
}

### Empregado

In [38]:
df["empregado"] = df["empregado"].str.lower()
df["empregado"] = df["empregado"].map(lambda x: unidecode(str(x)))
df["empregado"].unique()

array(['proprio', 'terceiro'], dtype=object)

### Classificação

In [39]:
df["classificacao"] = df["classificacao"].str.lower()
df["classificacao"] = df["classificacao"].map(lambda x: unidecode(str(x)))
df["classificacao"].unique()

array(['tipico com afastamento', 'trajeto com afastamento',
       'quase acidente', 'tipico sem afastamento',
       'trajeto sem afastamento', 'doenca ocupacional', 'fatalidade',
       'desvio critico'], dtype=object)

### Empresa

In [40]:
df["empresa"] = df["empresa"].str.lower()
df["empresa"] = df["empresa"].map(lambda x: unidecode(str(x)))
df["empresa"].unique()

array(['cgt eletrosul', 'chesf', 'eletronorte', 'eletrobras'],
      dtype=object)

### Fornecedor

In [41]:
df["fornecedor"] = df["fornecedor"].str.lower()
df["fornecedor"] = df["fornecedor"].map(lambda x: unidecode(str(x)))

df["fornecedor"] = df["fornecedor"].replace(replace_dict)
df["fornecedor"].unique()

array([nan, 'fasttel engenharia s.a',
       'joplin servicos de apoio administrativo eireli',
       'cca servicos e comercio ltda', 'vision',
       'montago construtora ltda', 'amazon construcoes e servicos eireli',
       'metacom servicos ', 'rp manutencao industrial eirelli',
       'vividence linhas de transmissao ltda', 'spandex',
       'rst engenharia e solucoes ltda',
       'especialy terceirizacao eireli ',
       'lideranca limpeza e conservacao ltda',
       'ts infraestrutura e engenharia s.a',
       'pi engenharia e construcoes ltda',
       'brasil recruta mao de obra eireli ', 'vividense',
       ' goetze lobato engenharia s.a. ',
       'plansul planejamento e consultoria ltda.',
       'ts infraestrutura e engenharia', 'neutron seguranca privada',
       'engevale - servicos de instalacoes e manutencoes eletricas',
       'dmf servicos especializados para construcao',
       'erel construcoes e empreendimentos',
       'tecmon montagens tecnicas industriais', 'hbf

### Colocando próprios com fornecedor como terceiro

In [42]:
df.loc[df["fornecedor"].notna(), "empregado"] = "terceiro"
print(df["empregado"].unique())


['proprio' 'terceiro']


### ID

In [43]:
df["id"] = df["id"].str.lower()
df["id"] = df["id"].map(lambda x: unidecode(str(x)))

df["id"] = df["id"].str.lstrip("\t")

df["id"] = df["id"].replace(replace_dict)

df_eletrosul = df.loc[df["empresa"] == "cgt eletrosul"]
df_proprio = df_eletrosul.loc[df_eletrosul["empregado"] == "proprio"]
df_proprio_notna = df_proprio.dropna(subset=["id"])

print(df_proprio_notna["id"].nunique())
print(df_proprio_notna["id"].unique())

# ! voltar e resolver os dois IDs na mesma linha


103
['1542803' '1533282' '1540857' '1540378' '210341' '1542829' '1536369'
 '1536145' '1533092' '1533050' '1536434' '1536682' '1527160' '1534892'
 '1542316' '1541714' '210137' '210359' '210154' '210231' '210220' '210354'
 '210083' '210280' '210225' '210026' '1533315' '210287' '210168' '1537375'
 '5000873' '210318' '210388' '1536343' '1520817' '614489' '21031'
 '1522334' '1535147' '1542051' '1539115' '1540526' '1533612' '11534123'
 '1542457' '210178' '210358' '1533943' '210244' '1537515' '1532135'
 '210342' '210213' '1536327' '1539355' '1532169' '1543067' '1536484'
 '1524174' '1536799' '1524489' '1540162' '1538836' '1531864' '9002552'
 '1539123' '210112' '1123408764' '1523324' '1537507' '1533852' '1533787'
 '1532010' '1542978' '210249' '337263' '1536799 e 1533399' '1536468'
 '1536228' '1540047' '337255' '1401843' '1541615' '210344' '1537333'
 '1531476' '338138' '338130' '9002643' '1542407' '1531682' '337287'
 '337150' '1533331' '1533737' '337608' '336536' '337288' '337593' '210135'
 '338

### Dia

In [44]:
df["dia"].unique()

array([11,  1,  7, 20, 24,  8, 31, 15, 14, 23, 26,  9, 17, 12, 13, 21, 28,
       19, 22,  5,  3, 10, 30,  2,  4, 18, 16, 25,  6, 27, 29])

### Mes

In [45]:
df["mes"].unique()

array([ 2,  3,  6,  9,  1,  5,  7,  8, 10, 11, 12,  4])

### Ano

In [46]:
df["ano"].unique()

array([2020, 2021, 2022, 2023, 2024])

### Descrição

In [47]:
df["descricao"].str.lower()
df["descricao"].map(lambda x: unidecode(str(x)))

df["descricao"] = df["descricao"].replace(replace_dict)

### Coordenadas

In [48]:
def processa_coordenada(value):
    if isinstance(value, str):
        value = value.replace(",", ".")  # Substitui vírgula por ponto
        value = value.replace("°", "")  # Remove "°"
        return float(value)

    return value


def corrige_coordenada(df):
    # Corrigir longitude digitada errada (número muito grande)
    df["longitude"] = df["longitude"].apply(
        lambda x: x / 100000 if pd.notna(x) and x < -100 else x
    )
    # Corrigir sinal das coordenadas trocado
    df["longitude"] = df["longitude"].apply(
        lambda x: x * (-1) if pd.notna(x) and x > 0 else x
    )
    # Corrigir vírgulas das coordenadas digitadas errado
    df["longitude"] = df["longitude"].apply(
        lambda x: x * 10 if pd.notna(x) and x > -10 else x
    )
    # Desconsiderar pontos na Antártica
    df = df[df["latitude"].apply(lambda x: pd.notna(x) and x > -40 if pd.notna(x) else True)]

    return df

Latitude

In [49]:
print(df[["latitude", "longitude"]].isna().sum())

print(df["latitude"].unique())
df["latitude"] = df["latitude"].apply(processa_coordenada)
print(df["latitude"].unique())

latitude     13
longitude    13
dtype: int64
['-29.9749205' '-24.10744879' '-26.1795003' '-24.110744879' '-29.2233266'
 '-9.373' '-12.7942' '-10.59693' '-10.56693' '-9.121' '-5.800921' '-9.363'
 '-9.353' '-9.383' '-7.51181' '-7.52181' '-5.15274' '-7.086907'
 '-7.106907' '-5.16274' '-8.04489' '-12.9339' '-10.66376' '-5.81921'
 '-5.82921' '-8.0326489' '-4.2818555' '-8.0216489' '-5.87199' '-3.852449'
 '-14.22967' '-8.0106489' '-10.52493' '-8.0016489' '-16.47205' '-10.9015'
 '-11.60715' '-8.75705' '-5.20064' '4.47306' '-22.95550095'
 '-14.887132322' '-23.5039313' '-19.50148383' '-11.73573715'
 '-22.52849125' '-19.40370178' '-20.19467772' '-23.70467781'
 '-21.73002813' '-16.79296983' '-27.65070522' '-31.5514' '-28.62' '-6.96'
 '-6.95' '-25.9688306' '-29.86081795' '-28.433567574' '-27.59083458'
 '-29.881795' '-27.2353096' '-20.5259397' '-27.62070522' '-27.63070522'
 nan '-9.370965' '-12.67283' '-12.61891' '-9.4133' '-6.974866' '-3.832449'
 '-9.521602' '-7.953534' '-8.07489' '-9.382364' '-8.0

Longitude

In [50]:
print(df["longitude"].unique())
df["longitude"] = df["longitude"].apply(processa_coordenada)
print(df["longitude"].unique())


[-51.6636476  -52.33699006 -50.4329802  -52.31369901 -51.3812348
 -38.2311     -38.42207    -38.26682    -38.36482    -38.32088
 -35.2393     -38.2711     -38.16211    -38.211      -34.99525
 -34.00199525 -38.354682   -42.820059   -34.9686     -34.94686
 -42.810059   -34.93058    -38.43       -37.46067    -35.22393
 -35.23293    -34.963058   -41.735495   -34.953058   -35.31747
 -38.593808   -39.46339    -34.943058   -38.36682    -54.59916
 -61.920734   -61.13727    -63.91356    -49.02332    -61.14638
 -43.19166332 -55.74855685 -46.16966497 -40.91886906 -49.0114858
 -44.56836322 -40.10685456 -40.29376961 -46.27878975 -41.3237705
 -49.2342857  -48.55237718 -53.650828   -52.88       -35.71
 -35.7        -51.6048167  -51.06179604 -48.98071791 -48.6172231
 -51.02079603 -48.6752054  -59.8460928  -48.51237718 -48.54237718
          nan -38.0755781  -38.33556    -38.38434    -40.8291
 -35.081992   -38.553808   -35.855012   -34.87125    -34.91058
 -35.915621   -34.923058   -35.865012   -35.9456

In [51]:
df = corrige_coordenada(df)
print(df[["latitude", "longitude"]].isna().sum())

latitude     13
longitude    13
dtype: int64


### Exportar o dataset

In [52]:
df = df.drop(columns=["unnamed: 0"])

pathUtil = "data/util/"
pathUtil = ajuste_path(pathUtil)

df.to_csv(pathUtil + "acidentes/" + "acidentes_preprocessado.csv", sep="@", encoding="utf-8", index=False)